NAME=AndOpenl
SRC=main.cpp ClapTrap.cpp
OBJ=$(SRC:.cpp=.o)
CC=clang++
CFLAGS=-Wall -Wextra -Werror -std=c++98

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

clean:
	rm -f $(OBJ) $(NAME)

fclean: clean

re: fclean all

.PHONY: all clean fclean re
